# Numpy

# Hola Jupyter Notebook
## Hola Jupyter Notebook
### Hola Jupyter Notebook
#### Hola Jupyter Notebook
##### Hola Jupyter Notebook

In [118]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [119]:
import numpy as np

# Arreglos

In [120]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [121]:
arr = np.array(([1,2,3],[4,5,6]))
print(arr)

[[1 2 3]
 [4 5 6]]


In [122]:
arr = np.array(([1,2,3],[4,5,6],[7,8,9]))
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [123]:
arr = np.array([1,2,3,4,5,6,7,8,9], ndmin=3)

print(arr.ndim)

print(arr)
print(arr[0])
print(arr[0][0])
print(arr[0][0][0])

    

3
[[[1 2 3 4 5 6 7 8 9]]]
[[1 2 3 4 5 6 7 8 9]]
[1 2 3 4 5 6 7 8 9]
1


In [124]:
arr = np.zeros((2,2))

print(arr)

[[0. 0.]
 [0. 0.]]


In [125]:
arr = np.zeros((3,3))

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [126]:
arr = np.zeros((4,4))

print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [127]:
arr = np.zeros((5,5))

print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [128]:
arr = np.zeros((5,1))

print(arr)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [129]:
arr = np.zeros((5,2))

print(arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [130]:
arr = np.zeros((5,3))

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [131]:
arr = np.zeros((5,4))

print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [132]:
arr = np.zeros((1,5))

print(arr)

[[0. 0. 0. 0. 0.]]


In [133]:
arr = np.zeros((2,5))

print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [134]:
arr = np.zeros((3,5))

print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [135]:
arr = np.zeros((4,5))

print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [136]:
arr = np.zeros((5,5))

print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [137]:
arr = np.ones((5,5))

print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [138]:
arr = np.ones((15,15))

print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [139]:
arr = np.zeros((2,2))

print(arr)

[[0. 0.]
 [0. 0.]]


In [140]:
arr = np.zeros((3,3))

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [141]:
arr = np.zeros((3,3))

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [142]:
arr = np.zeros((4,4))

print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [143]:
arr = np.zeros((5,5))

print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [144]:
arr = np.zeros((5,4))

print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [145]:
arr = np.zeros((5,3))

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [146]:
arr = np.zeros((5,2))

print(arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [147]:
arr = np.zeros((5,1))

print(arr)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [148]:
arr = np.zeros((4,5))

print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [149]:
arr = np.zeros((3,5))

print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [150]:
arr = np.zeros((2,5))

print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [151]:
arr = np.zeros((1,5))

print(arr)

[[0. 0. 0. 0. 0.]]


In [152]:
arr = np.random.rand(1,1)

print(arr)

[[0.56252609]]


In [153]:
arr = np.random.rand(2,2)

print(arr)

[[0.48779245 0.83695002]
 [0.8264649  0.42405356]]


In [154]:
arr = np.random.rand(3,3)

print(arr)

[[0.29572615 0.48734626 0.18935493]
 [0.4387873  0.26208158 0.90188182]
 [0.56434064 0.37911352 0.71856197]]


In [155]:
arr = np.random.rand(4,4)

print(arr)

[[0.90623763 0.35818218 0.28851144 0.23277951]
 [0.23329967 0.72630348 0.21158321 0.39191855]
 [0.0096078  0.3872628  0.3764393  0.43013539]
 [0.37060369 0.36505961 0.67570321 0.99753548]]


In [156]:
arr = np.random.rand(5,5)

print(arr)

[[0.83670145 0.21005351 0.08496098 0.44931162 0.27255468]
 [0.41102171 0.02662248 0.12922865 0.98131155 0.45659925]
 [0.4370681  0.70010721 0.5037661  0.19957003 0.67211685]
 [0.80042097 0.94767871 0.6354659  0.40700003 0.41047905]
 [0.53112373 0.31585175 0.74367087 0.23441404 0.70961607]]


# Operaciones aritméticas con Arreglos

### Suma

In [157]:
arr00 = [1,2,3]
arr01 = [4,5,6]

arr03 = np.add(arr00,arr01)

print(arr03)

[5 7 9]


### Resta

In [158]:
arr00 = [1,2,3]
arr01 = [4,5,6]

arr03 = np.subtract(arr01,arr00)

print(arr03)

[3 3 3]


### Multiplicacion

In [159]:
arr00 = [1,2,3]
arr01 = [4,5,6]

arr03 = np.multiply(arr01,arr00)

print(arr03)

[ 4 10 18]


### Division

In [160]:
arr00 = [1,2,3]
arr01 = [4,5,6]

arr03 = np.divide(arr01,arr00)

print(arr03)

[4.  2.5 2. ]


# Operaciones de Estadistica con Arreglos

### Media

In [161]:
arr = [1,5,7]

media = np.mean(arr)

print(media)

4.333333333333333


### Mediana

In [162]:
arr = [1,5,7]

mediana = np.mean(arr)            

print(mediana)

4.333333333333333


### Maximo

In [163]:
arr = [1,5,7]

maximo = np.max(arr)            

print(maximo)

7


### Minimo

In [164]:
arr = [1,5,7]

minimo = np.min(arr)            

print(minimo)

1


# Indexación

In [165]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[0])

1


In [166]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[1])

2


In [167]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[2])

3


In [168]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[3])

4


In [169]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[4])

5


In [170]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[-1])

10


In [171]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[-1])

10


In [172]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[-2])

9


In [173]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[-3])

8


In [174]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[-4])

7


In [175]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[-5])

6


In [180]:
arr = np.array(([1,2,3],[4,5,6]))

print(arr[1,1])

5


In [182]:
arr = np.array(([1,2,3],[4,5,6]))

print(arr[0,0])
print(arr[0,0])
print(arr[0,0])
print(arr[0,0])
print(arr[0,0])


1
