# Numpy

# Hola Jupyter Notebook
## Hola Jupyter Notebook
### Hola Jupyter Notebook
#### Hola Jupyter Notebook
##### Hola Jupyter Notebook

In [110]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [111]:
import numpy as np

# Arreglos

In [112]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [113]:
arr = np.array(([1,2,3],[4,5,6]))
print(arr)

[[1 2 3]
 [4 5 6]]


In [114]:
arr = np.array(([1,2,3],[4,5,6],[7,8,9]))
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [115]:
arr = np.array([1,2,3,4,5,6,7,8,9], ndmin=3)

print(arr.ndim)

print(arr)
print(arr[0])
print(arr[0][0])
print(arr[0][0][0])

    

3
[[[1 2 3 4 5 6 7 8 9]]]
[[1 2 3 4 5 6 7 8 9]]
[1 2 3 4 5 6 7 8 9]
1


In [116]:
arr = np.zeros((2,2))

print(arr)

[[0. 0.]
 [0. 0.]]


In [117]:
arr = np.zeros((3,3))

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [118]:
arr = np.zeros((4,4))

print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [119]:
arr = np.zeros((5,5))

print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [120]:
arr = np.zeros((5,1))

print(arr)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [121]:
arr = np.zeros((5,2))

print(arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [122]:
arr = np.zeros((5,3))

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [123]:
arr = np.zeros((5,4))

print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [124]:
arr = np.zeros((1,5))

print(arr)

[[0. 0. 0. 0. 0.]]


In [125]:
arr = np.zeros((2,5))

print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [126]:
arr = np.zeros((3,5))

print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [127]:
arr = np.zeros((4,5))

print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [128]:
arr = np.zeros((5,5))

print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [129]:
arr = np.ones((5,5))

print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [130]:
arr = np.ones((15,15))

print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [131]:
arr = np.zeros((2,2))

print(arr)

[[0. 0.]
 [0. 0.]]


In [132]:
arr = np.zeros((3,3))

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [133]:
arr = np.zeros((3,3))

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [134]:
arr = np.zeros((4,4))

print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [135]:
arr = np.zeros((5,5))

print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [136]:
arr = np.zeros((5,4))

print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [137]:
arr = np.zeros((5,3))

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [138]:
arr = np.zeros((5,2))

print(arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [139]:
arr = np.zeros((5,1))

print(arr)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [140]:
arr = np.zeros((4,5))

print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [141]:
arr = np.zeros((3,5))

print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [142]:
arr = np.zeros((2,5))

print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [143]:
arr = np.zeros((1,5))

print(arr)

[[0. 0. 0. 0. 0.]]


In [144]:
arr = np.random.rand(1,1)

print(arr)

[[0.12796911]]


In [145]:
arr = np.random.rand(2,2)

print(arr)

[[0.49698742 0.8863576 ]
 [0.15573243 0.11949566]]


In [146]:
arr = np.random.rand(3,3)

print(arr)

[[0.32885651 0.32233941 0.73797952]
 [0.97229069 0.11793514 0.6976538 ]
 [0.14734271 0.94737939 0.81244295]]


In [147]:
arr = np.random.rand(4,4)

print(arr)

[[0.27579866 0.86592738 0.73542717 0.2152342 ]
 [0.05865344 0.32066111 0.27194458 0.19934562]
 [0.48000774 0.89160425 0.17310634 0.80501646]
 [0.56615014 0.16347439 0.61697339 0.53213002]]


In [148]:
arr = np.random.rand(5,5)

print(arr)

[[0.68637604 0.97910916 0.872844   0.86682965 0.15617736]
 [0.99275123 0.67340985 0.53768348 0.50685538 0.58261296]
 [0.36563487 0.9468286  0.5923928  0.59258639 0.51706074]
 [0.60002362 0.13429549 0.84786196 0.17312182 0.6685512 ]
 [0.72722486 0.8912115  0.96731832 0.40467347 0.39928858]]


# Operaciones aritméticas con Arreglos

### Suma

In [149]:
arr00 = [1,2,3]
arr01 = [4,5,6]

arr03 = np.add(arr00,arr01)

print(arr03)

[5 7 9]


### Resta

In [150]:
arr00 = [1,2,3]
arr01 = [4,5,6]

arr03 = np.subtract(arr01,arr00)

print(arr03)

[3 3 3]


### Multiplicacion

In [151]:
arr00 = [1,2,3]
arr01 = [4,5,6]

arr03 = np.multiply(arr01,arr00)

print(arr03)

[ 4 10 18]


### Division

In [152]:
arr00 = [1,2,3]
arr01 = [4,5,6]

arr03 = np.divide(arr01,arr00)

print(arr03)

[4.  2.5 2. ]


# Operaciones de Estadistica con Arreglos

### Media

In [153]:
arr = [1,5,7]

media = np.mean(arr)

print(media)

4.333333333333333


### Mediana

In [154]:
arr = [1,5,7]

mediana = np.mean(arr)            

print(mediana)

4.333333333333333


### Maximo

In [155]:
arr = [1,5,7]

maximo = np.max(arr)            

print(maximo)

7


### Minimo

In [156]:
arr = [1,5,7]

minimo = np.min(arr)            

print(minimo)

1


# Indexación

In [157]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[0])

1


In [158]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[1])

2


In [159]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[2])

3


In [160]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[3])

4


In [161]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[4])

5


In [162]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[-1])

10


In [163]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[-1])

10


In [164]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[-2])

9


In [165]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[-3])

8


In [166]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[-4])

7


In [167]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[-5])

6


In [168]:
arr = np.array(([1,2,3],[4,5,6]))

print(arr[1,1])

5


In [169]:
arr = np.array(([1,2,3],[4,5,6]))

print(arr[0,0])
print(arr[0,1])
print(arr[0,2])
print("")
print(arr[1,0])
print(arr[1,1])
print(arr[1,2])



1
2
3

4
5
6


In [170]:
arr = np.array((1,2,3,4,5,6))

print(arr[1:4])


[2 3 4]


In [171]:
arr = np.array((1,2,3,4,5,6))

print(arr[1:4:2])

[2 4]


In [172]:
arr = np.array((1,2,3,4,5,6,7,8,9,10))

print(arr[0:8:2])

[1 3 5 7]


In [173]:
arr = np.array((1,2,3,4,5,6,7,8,9,10,11,12))

print(arr[0:7:2])

[1 3 5 7]


In [174]:
arr = np.array((1,2,3,4,5,6,7,8,9,10,11,12))

print(arr[::])

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [175]:
arr = np.array((1,2,3,4,5,6,7,8,9,10,11,12))

print(arr[::1])

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [176]:
arr = np.array((1,2,3,4,5,6,7,8,9,10,11,12))

print(arr[::2])

[ 1  3  5  7  9 11]


In [177]:
arr = np.array((1,2,3,4,5,6,7,8,9,10,11,12))

print(arr[::3])

[ 1  4  7 10]


# Slicing

In [183]:
arr = np.array((1,2,3,4,5,6,7,8,9,10,11,12,13,14,15))

print(arr[1::2])

[ 2  4  6  8 10 12 14]


In [184]:
arr = np.array((1,2,3,4,5,6,7,8,9,10,11,12,13,14,15))

print(arr[1::3])

[ 2  5  8 11 14]


In [185]:
arr = np.array((1,2,3,4,5,6,7,8,9,10,11,12,13,14,15))

print(arr[1::4])

[ 2  6 10 14]
