# Numpy

# Hola Jupyter Notebook
## Hola Jupyter Notebook
### Hola Jupyter Notebook
#### Hola Jupyter Notebook
##### Hola Jupyter Notebook

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

# Arreglos

In [4]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [5]:
arr = np.array(([1,2,3],[4,5,6]))
print(arr)

[[1 2 3]
 [4 5 6]]


In [6]:
arr = np.array(([1,2,3],[4,5,6],[7,8,9]))
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
arr = np.array([1,2,3,4,5,6,7,8,9], ndmin=3)

print(arr.ndim)

print(arr)
print(arr[0])
print(arr[0][0])
print(arr[0][0][0])

    

3
[[[1 2 3 4 5 6 7 8 9]]]
[[1 2 3 4 5 6 7 8 9]]
[1 2 3 4 5 6 7 8 9]
1


In [8]:
arr = np.zeros((2,2))

print(arr)

[[0. 0.]
 [0. 0.]]


In [9]:
arr = np.zeros((3,3))

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
arr = np.zeros((4,4))

print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
arr = np.zeros((5,5))

print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [12]:
arr = np.zeros((5,1))

print(arr)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [13]:
arr = np.zeros((5,2))

print(arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [14]:
arr = np.zeros((5,3))

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [15]:
arr = np.zeros((5,4))

print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [16]:
arr = np.zeros((1,5))

print(arr)

[[0. 0. 0. 0. 0.]]


In [17]:
arr = np.zeros((2,5))

print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [18]:
arr = np.zeros((3,5))

print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [19]:
arr = np.zeros((4,5))

print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [20]:
arr = np.zeros((5,5))

print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [21]:
arr = np.ones((5,5))

print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [22]:
arr = np.ones((15,15))

print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [23]:
arr = np.zeros((2,2))

print(arr)

[[0. 0.]
 [0. 0.]]


In [24]:
arr = np.zeros((3,3))

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [25]:
arr = np.zeros((3,3))

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [26]:
arr = np.zeros((4,4))

print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [27]:
arr = np.zeros((5,5))

print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [28]:
arr = np.zeros((5,4))

print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [29]:
arr = np.zeros((5,3))

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [30]:
arr = np.zeros((5,2))

print(arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [31]:
arr = np.zeros((5,1))

print(arr)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [32]:
arr = np.zeros((4,5))

print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [33]:
arr = np.zeros((3,5))

print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [34]:
arr = np.zeros((2,5))

print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [35]:
arr = np.zeros((1,5))

print(arr)

[[0. 0. 0. 0. 0.]]


In [36]:
arr = np.random.rand(1,1)

print(arr)

[[0.08052339]]


In [37]:
arr = np.random.rand(2,2)

print(arr)

[[0.92233313 0.78351912]
 [0.09675944 0.15636281]]


In [38]:
arr = np.random.rand(3,3)

print(arr)

[[0.75419299 0.74319816 0.1026746 ]
 [0.08645326 0.14559872 0.39651778]
 [0.90183902 0.65223353 0.82122635]]


In [39]:
arr = np.random.rand(4,4)

print(arr)

[[0.27124041 0.23544096 0.20430564 0.70552578]
 [0.75452152 0.07238784 0.30669792 0.95158543]
 [0.59337456 0.2279595  0.68705135 0.30094421]
 [0.61308299 0.30491465 0.71794655 0.53017061]]


In [40]:
arr = np.random.rand(5,5)

print(arr)

[[0.79280802 0.77982143 0.18163071 0.12015956 0.6637091 ]
 [0.64806978 0.21900212 0.45906071 0.72372037 0.98747003]
 [0.99431862 0.29982928 0.46013312 0.7293271  0.06623622]
 [0.17790006 0.85957456 0.35162124 0.06972669 0.08495087]
 [0.31439126 0.87545859 0.01562705 0.26186539 0.08023723]]


# Operaciones aritméticas con Arreglos

### Suma

In [41]:
arr00 = [1,2,3]
arr01 = [4,5,6]

arr03 = np.add(arr00,arr01)

print(arr03)

[5 7 9]


### Resta

In [42]:
arr00 = [1,2,3]
arr01 = [4,5,6]

arr03 = np.subtract(arr01,arr00)

print(arr03)

[3 3 3]


### Multiplicacion

In [43]:
arr00 = [1,2,3]
arr01 = [4,5,6]

arr03 = np.multiply(arr01,arr00)

print(arr03)

[ 4 10 18]


### Division

In [44]:
arr00 = [1,2,3]
arr01 = [4,5,6]

arr03 = np.divide(arr01,arr00)

print(arr03)

[4.  2.5 2. ]


# Operaciones de Estadistica con Arreglos

### Media

In [45]:
arr = [1,5,7]

media = np.mean(arr)

print(media)

4.333333333333333


### Mediana

In [46]:
arr = [1,5,7]

mediana = np.mean(arr)            

print(mediana)

4.333333333333333


### Maximo

In [47]:
arr = [1,5,7]

maximo = np.max(arr)            

print(maximo)

7


### Minimo

In [48]:
arr = [1,5,7]

minimo = np.min(arr)            

print(minimo)

1


# Indexación

In [49]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[0])

1


In [50]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[1])

2


In [51]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[2])

3


In [52]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[3])

4


In [53]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[4])

5


In [54]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[-1])

10


In [55]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[-1])

10


In [56]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[-2])

9


In [57]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[-3])

8


In [58]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[-4])

7


In [59]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[-5])

6


In [60]:
arr = np.array(([1,2,3],[4,5,6]))

print(arr[1,1])

5


In [73]:
arr = np.array(([1,2,3],[4,5,6]))

print(arr[0,0])
print(arr[0,1])
print(arr[0,2])
print("")
print(arr[1,0])
print(arr[1,1])
print(arr[1,2])



1
2
3

4
5
6


In [75]:
arr = np.array((1,2,3,4,5,6))

print(arr[1:4])


[2 3 4]


In [76]:
arr = np.array((1,2,3,4,5,6))

print(arr[1:4:2])

[2 4]


In [87]:
arr = np.array((1,2,3,4,5,6,7,8,9,10))

print(arr[0:8:2])

[1 3 5 7]


In [99]:
arr = np.array((1,2,3,4,5,6,7,8,9,10,11,12))

print(arr[0:7:2])

[1 3 5 7]


In [107]:
arr = np.array((1,2,3,4,5,6,7,8,9,10,11,12))

print(arr[::])

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [105]:
arr = np.array((1,2,3,4,5,6,7,8,9,10,11,12))

print(arr[::1])

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [108]:
arr = np.array((1,2,3,4,5,6,7,8,9,10,11,12))

print(arr[::2])

[ 1  3  5  7  9 11]


In [109]:
arr = np.array((1,2,3,4,5,6,7,8,9,10,11,12))

print(arr[::3])

[ 1  4  7 10]
