# Numpy

# Hola Jupyter Notebook
## Hola Jupyter Notebook
### Hola Jupyter Notebook
#### Hola Jupyter Notebook
##### Hola Jupyter Notebook

In [9]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [10]:
import numpy as np

# Arreglos

In [11]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [12]:
arr = np.array(([1,2,3],[4,5,6]))
print(arr)

[[1 2 3]
 [4 5 6]]


In [13]:
arr = np.array(([1,2,3],[4,5,6],[7,8,9]))
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
arr = np.array([1,2,3,4,5,6,7,8,9], ndmin=3)

print(arr.ndim)

print(arr)
print(arr[0])
print(arr[0][0])
print(arr[0][0][0])

    

3
[[[1 2 3 4 5 6 7 8 9]]]
[[1 2 3 4 5 6 7 8 9]]
[1 2 3 4 5 6 7 8 9]
1


In [15]:
arr = np.zeros((2,2))

print(arr)

[[0. 0.]
 [0. 0.]]


In [16]:
arr = np.zeros((3,3))

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [17]:
arr = np.zeros((4,4))

print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [18]:
arr = np.zeros((5,5))

print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [19]:
arr = np.zeros((5,1))

print(arr)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [20]:
arr = np.zeros((5,2))

print(arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [21]:
arr = np.zeros((5,3))

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [22]:
arr = np.zeros((5,4))

print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [23]:
arr = np.zeros((1,5))

print(arr)

[[0. 0. 0. 0. 0.]]


In [24]:
arr = np.zeros((2,5))

print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [25]:
arr = np.zeros((3,5))

print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [26]:
arr = np.zeros((4,5))

print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [27]:
arr = np.zeros((5,5))

print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [28]:
arr = np.ones((5,5))

print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [29]:
arr = np.ones((15,15))

print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [30]:
arr = np.zeros((2,2))

print(arr)

[[0. 0.]
 [0. 0.]]


In [31]:
arr = np.zeros((3,3))

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [32]:
arr = np.zeros((3,3))

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [33]:
arr = np.zeros((4,4))

print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [34]:
arr = np.zeros((5,5))

print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [35]:
arr = np.zeros((5,4))

print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [36]:
arr = np.zeros((5,3))

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [37]:
arr = np.zeros((5,2))

print(arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [38]:
arr = np.zeros((5,1))

print(arr)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [39]:
arr = np.zeros((4,5))

print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [40]:
arr = np.zeros((3,5))

print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [41]:
arr = np.zeros((2,5))

print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [42]:
arr = np.zeros((1,5))

print(arr)

[[0. 0. 0. 0. 0.]]


In [43]:
arr = np.random.rand(1,1)

print(arr)

[[0.24359882]]


In [44]:
arr = np.random.rand(2,2)

print(arr)

[[0.95418982 0.23351562]
 [0.8909321  0.59658388]]


In [45]:
arr = np.random.rand(3,3)

print(arr)

[[0.31047222 0.55817569 0.73153198]
 [0.42673556 0.05544585 0.61776042]
 [0.89735144 0.01428341 0.8269402 ]]


In [46]:
arr = np.random.rand(4,4)

print(arr)

[[0.40509527 0.6920714  0.19935463 0.94415517]
 [0.46438537 0.79220969 0.89765788 0.42019453]
 [0.64676362 0.08264988 0.55352023 0.03702168]
 [0.57642004 0.79406759 0.55986731 0.67068485]]


In [47]:
arr = np.random.rand(5,5)

print(arr)

[[0.22084271 0.43384213 0.95146223 0.37771376 0.8223761 ]
 [0.12268268 0.08592644 0.93530477 0.5273063  0.70741384]
 [0.75736798 0.0419023  0.68086347 0.56498137 0.92516314]
 [0.03645718 0.06027179 0.10974251 0.011931   0.77641283]
 [0.78521779 0.44963276 0.83633218 0.07723259 0.51261123]]


# Operaciones aritméticas con Arreglos

### Suma

In [48]:
arr00 = [1,2,3]
arr01 = [4,5,6]

arr03 = np.add(arr00,arr01)

print(arr03)

[5 7 9]


### Resta

In [49]:
arr00 = [1,2,3]
arr01 = [4,5,6]

arr03 = np.subtract(arr01,arr00)

print(arr03)

[3 3 3]


### Multiplicacion

In [50]:
arr00 = [1,2,3]
arr01 = [4,5,6]

arr03 = np.multiply(arr01,arr00)

print(arr03)

[ 4 10 18]


### Division

In [51]:
arr00 = [1,2,3]
arr01 = [4,5,6]

arr03 = np.divide(arr01,arr00)

print(arr03)

[4.  2.5 2. ]


# Operaciones de Estadistica con Arreglos

### Media

In [52]:
arr = [1,5,7]

media = np.mean(arr)

print(media)

4.333333333333333


### Mediana

In [53]:
arr = [1,5,7]

mediana = np.mean(arr)            

print(mediana)

4.333333333333333


### Maximo

In [54]:
arr = [1,5,7]

maximo = np.max(arr)            

print(maximo)

7


In [ ]:
### Minimo

In [55]:
arr = [1,5,7]

minimo = np.min(arr)            

print(minimo)

1
