# NumPy

In [1]:
import numpy as np

### Arreglos

In [2]:
arr = np.array([1,2,3])

print(arr)

[1 2 3]


In [3]:
arr = np.array(([1,2,3], [4,5,6]))

print(arr)

[[1 2 3]
 [4 5 6]]


In [4]:
arr = np.array(([1,2,3], [4,5,6], [7,8,9]))

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
arr = np.array([1,2,3,4,5,6], ndmin=3)

print(arr.ndim)

print(arr)
print(arr[0])
print(arr[0][0])
print(arr[0][0][0])

3
[[[1 2 3 4 5 6]]]
[[1 2 3 4 5 6]]
[1 2 3 4 5 6]
1


In [6]:
arr = np.zeros((2,2))

print(arr)

[[0. 0.]
 [0. 0.]]


In [7]:
arr = np.ones((3,3))

print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:
arr = np.random.rand(3,3)

print(arr)

[[0.28297492 0.38476376 0.74266131]
 [0.11030768 0.23158634 0.85637173]
 [0.35593364 0.32081284 0.70176997]]


### Operaciones

In [9]:
arr1 = [1,2,3]

arr2 = [4,5,6]

arr3 = np.add(arr1, arr2)

print(arr3)

[5 7 9]


In [10]:
arr2 = [1,2,3]

arr1 = [4,5,6]

arr3 = np.subtract(arr1, arr2)

print(arr3)

[3 3 3]


In [11]:
arr1 = [1,2,3]

arr2 = [4,5,6]

arr3 = np.multiply(arr1, arr2)

print(arr3)

[ 4 10 18]


In [12]:
arr1 = [1,2,3]

arr2 = [4,5,6]

arr3 = np.divide(arr1, arr2)

print(arr3)

[0.25 0.4  0.5 ]


### Agregación

In [13]:
arr = [1, 5, 7]

media = np.mean(arr)

print(media)    

4.333333333333333


In [14]:

arr = [1, 5, 7]

mediana = np.median(arr)

print(mediana)

5.0


In [15]:
arr = [1, 5, 7]

maximo = np.max(arr)

print(maximo)

7


In [16]:
arr = [1, 5, 7]

minimo = np.min(arr)

print(minimo)

1


### Indexación

In [17]:
arr = np.array([1,2,3,4,5,6])

print(arr[0])

1


In [18]:
arr = np.array([1,2,3,4,5,6])

print(arr[-1])

6


In [19]:
arr = np.array(([1,2,3], [4,5,6]))

print(arr[1, 2])

6


### Slicing

In [20]:
arr = np.array([1,2,3,4,5,6])

print(arr[1:4])

[2 3 4]


In [21]:
arr = np.array([1,2,3,4,5,6])

print(arr[1:4:2])

[2 4]


In [22]:
arr = np.array([1,2,3,4,5,6])

print(arr[::2])

[1 3 5]


### Tipos de datos

In [23]:
import numpy as np

arr = np.array(["b", "a"])

print(arr.dtype)

<U1


In [24]:
import numpy as np

arr = np.array([1.1, 2.5])

print(arr.dtype)

float64


In [25]:
arr = np.array([1, 2, 3], dtype='S')
    # 'i' = integer (entero)
    # 'b' = booleano
    # 'f' = flotante
    # 'M' = datetime
    # 'O' = objeto
    # 'S' = string (cadena)

print(arr)

[b'1' b'2' b'3']


In [26]:
arr = np.array([1.1, 2.1, 3.1])

print("pre", arr)

nuevo_arr = arr.astype('i')

print("post", nuevo_arr)

pre [1.1 2.1 3.1]
post [1 2 3]


### Copy vs View

In [27]:
arr = np.array([1,2,3])


x = arr.copy()
y = arr.view()

print("arr", arr)
print("x", x)
print("y", y)

arr[0] = 0

print("arr", arr)
print("x", x)
print("y", y)

arr [1 2 3]
x [1 2 3]
y [1 2 3]
arr [0 2 3]
x [1 2 3]
y [0 2 3]


In [28]:
arr = np.array([1,2,4])

print("arr", arr)

x = arr.view()

print("x", x)

arr [1 2 4]
x [1 2 4]


### Concatenar

In [29]:
arr1 = np.array([1,2,3])

print("arr1", arr1)

arr2 = np.array([4,5,6])

print("arr2", arr2)

arr3 = np.concatenate((arr1, arr2))

print("arr3", arr3)

arr1 [1 2 3]
arr2 [4 5 6]
arr3 [1 2 3 4 5 6]


### Búsqueda

In [30]:
arr = np.array([1, 2, 2, 4, 5, 5, 4])

x = np.where(arr == 4)

print(x)

(array([3, 6], dtype=int64),)


### Ordenar

In [31]:
arr = np.array([2, 5, 6, 4, 1, 3])

x = np.sort(arr)

print(x)

[1 2 3 4 5 6]


# Pandas

In [32]:
import pandas as pd

### Series

In [33]:
a = np.array([1,2,3])

srs = pd.Series(a)

print(srs)
print(srs[0])

0    1
1    2
2    3
dtype: int32
1


In [34]:
srs = pd.Series(a, index = ["x", "y", "z"])

print(srs)
print(srs["y"])

x    1
y    2
z    3
dtype: int32
2


In [35]:
pasos = {
    "lunes" : 440,
    "martes" : 620,
    "miercoles" : 700,
    "jueves" : 500,
    "viernes" : 150
}

srs = pd.Series(pasos)

print(srs)

lunes        440
martes       620
miercoles    700
jueves       500
viernes      150
dtype: int64


In [36]:
srs = pd.Series(pasos, index = ["martes", "jueves"])

print(srs)

martes    620
jueves    500
dtype: int64


### DataFrame

In [37]:
mydataset = {
  'operador': ["John Doe", "Sr. X", "Lorem ipsum"],
  'no. reloj': [101, 202, 303]
}

df = pd.DataFrame(mydataset)

print(df)

      operador  no. reloj
0     John Doe        101
1        Sr. X        202
2  Lorem ipsum        303


In [38]:
df.loc[0]

operador     John Doe
no. reloj         101
Name: 0, dtype: object

In [39]:
df['no. reloj']

0    101
1    202
2    303
Name: no. reloj, dtype: int64

In [40]:
df[df['no. reloj'] > 101]

operador  no. reloj
1        Sr. X        202
2  Lorem ipsum        303

In [41]:
df['asistencia'] = [True, False, True]

In [42]:
print(df)

      operador  no. reloj  asistencia
0     John Doe        101        True
1        Sr. X        202       False
2  Lorem ipsum        303        True


In [43]:
print(df.loc[0])

operador      John Doe
no. reloj          101
asistencia        True
Name: 0, dtype: object


In [44]:
print(df.loc[[0, 1]])

   operador  no. reloj  asistencia
0  John Doe        101        True
1     Sr. X        202       False


In [45]:
df = pd.DataFrame(mydataset, index = ["CEO", "COO", "CFO"])

print(df)

        operador  no. reloj
CEO     John Doe        101
COO        Sr. X        202
CFO  Lorem ipsum        303


In [46]:
print(df.loc["CEO"])

operador     John Doe
no. reloj         101
Name: CEO, dtype: object


In [47]:
print(df.loc[["CEO", "COO"]])

     operador  no. reloj
CEO  John Doe        101
COO     Sr. X        202


### Vistas

In [55]:
# df = pd.read_csv("/Users/mapko/OneDrive/Desktop/Python 3 Intermedio/Perfil de estudiante.csv")

df = pd.read_csv("../Python 3 Intermedio/Perfil de estudiante.csv")


df

Marca temporal  \
0    2023/06/27 7:42:12 p. m. GMT-6   
1    2023/06/27 7:42:28 p. m. GMT-6   
2    2023/06/27 7:42:44 p. m. GMT-6   
3    2023/06/27 7:42:52 p. m. GMT-6   
4    2023/06/27 7:42:56 p. m. GMT-6   
5    2023/06/27 7:42:57 p. m. GMT-6   
6    2023/06/27 7:42:57 p. m. GMT-6   
7    2023/06/27 7:43:04 p. m. GMT-6   
8    2023/06/27 7:43:10 p. m. GMT-6   
9    2023/06/27 7:43:12 p. m. GMT-6   
10   2023/06/27 7:43:12 p. m. GMT-6   
11   2023/06/27 7:43:16 p. m. GMT-6   
12   2023/06/27 7:43:16 p. m. GMT-6   
13   2023/06/27 7:43:29 p. m. GMT-6   
14   2023/06/27 7:43:34 p. m. GMT-6   
15   2023/06/27 7:43:50 p. m. GMT-6   
16   2023/06/27 7:44:01 p. m. GMT-6   
17   2023/06/27 7:44:01 p. m. GMT-6   
18   2023/06/27 7:44:12 p. m. GMT-6   
19   2023/06/27 7:44:14 p. m. GMT-6   
20   2023/06/27 7:44:17 p. m. GMT-6   
21   2023/06/27 7:44:20 p. m. GMT-6   
22   2023/06/27 7:44:25 p. m. GMT-6   
23   2023/06/27 7:44:30 p. m. GMT-6   
24   2023/06/27 7:44:31 p. m. GMT-6   
25   2023/06/27 7:45:04 p. m. GMT-6   
26   2023/06/27 7:45:37 p. m. GMT-6   
27   2023/06/27 7:45:45 p. m. GMT-6   
28   2023/06/27 7:46:10 p. m. GMT-6   
29   2023/06/27 7:46:14 p. m. GMT-6   
30   2023/06/27 7:46:28 p. m. GMT-6   
31   2023/06/27 7:46:32 p. m. GMT-6   
32   2023/06/27 7:46:37 p. m. GMT-6   
33   2023/06/27 7:49:23 p. m. GMT-6   
34   2023/06/27 7:51:23 p. m. GMT-6   
35   2023/06/27 7:55:00 p. m. GMT-6   
36   2023/06/27 8:05:42 p. m. GMT-6   
37   2023/06/27 8:22:29 p. m. GMT-6   
38  2023/06/27 10:02:11 p. m. GMT-6   
39  2023/06/27 10:31:28 p. m. GMT-6   
40  2023/06/28 10:12:04 p. m. GMT-6   
41   2023/06/29 2:00:51 a. m. GMT-6   
42   2023/07/03 1:55:24 p. m. GMT-6   

                          1.- ¿De dónde eres? 2.- ¿Cuántos años tienes?  \
0                                  Cd. Juárez             Entre 21 y 24   
1                        chihuahua, chihuahua             Entre 21 y 24   
2                         Chihuahua Chihuahua             Entre 18 y 20   
3                         Chihuahua Chihuahua             Entre 21 y 24   
4                            Chihuahua, Chih.                 Más de 30   
5                                      Puebla             Entre 21 y 24   
6                             Cd. Juarez Chih                 Más de 30   
7                               Ciudad Juarez             Entre 21 y 24   
8                              Aguascalientes             Entre 18 y 20   
9                            Cd Juarez, Chih.             Entre 21 y 24   
10                                     Juárez             Entre 21 y 24   
11                                 El Paso TX             Entre 18 y 20   
12                       Cuauhtemoc Chihuahua                 Más de 30   
13                                Cd. Juárez              Entre 21 y 24   
14                                    Hidalgo             Entre 25 y 29   
15                          Cd. Juarez, Chih.             Entre 21 y 24   
16                       Cd. Juarez Chihuahua                 Más de 30   
17             Ciudad Juarez Chihuahua Mexico             Entre 21 y 24   
18                              Ciudad Juarez                 Más de 30   
19                           Chihuahua, Chih.                 Más de 30   
20                              Ciudad Juarez             Entre 18 y 20   
21               Cd Juárez Chihuahua, México.                 Más de 30   
22                              Ciudad Juárez                 Más de 30   
23                                 Cd. Juárez             Entre 25 y 29   
24                                     Juarez             Entre 25 y 29   
25                     Cd. Juárez, Chihuahua              Entre 18 y 20   
26                            Aguascalientes              Entre 21 y 24   
27                                 Cd. Juarez             Entre 15 y 17   
28  San Francisco de los Romo, Aguascalientes             Entre 18 y 20   
29                                  Chihuahua         

In [ ]:
df.head()

In [ ]:
df.tail()

In [ ]:
df.info()

### CSV

In [ ]:



df = pd.read_csv('Perfil de estudiante.csv')

print(df.to_string())

### JSON

In [ ]:
df = pd.read_json("dataset.json")

print(df.to_string())

### Limpieza de datos

In [ ]:
data = {
    'Nombre': ['Juan', 'María', 'Pedro', 'Ana', 'Luis'],
    'Edad': [25, 32, None, 42, 28],
    'Fecha': ['31/01/2020', '31/01/2020', None, '31/01/2020', '01/31/2020'],
    'Género': ['M', 'F', None, 'F', 'M'],
    'Ciudad': ['Madrid', None, 'Madrid', 'Valencia', 'Barcelona'],
    'Altura': [175, 163, 180, 158, 170],
    'Peso': [70, None, 80, 60, 75],
    'Ingresos': [50000, 60000, 40000, None, 55000]
}

In [ ]:
df = pd.DataFrame(data)

print(df.to_string())

In [ ]:
mediana_edad = df['Edad'].median()

print(mediana_edad)

In [ ]:
df['Edad'].fillna(mediana_edad, inplace=True)

print(df)

In [ ]:
df.loc[4, "Fecha"] = "31/01/2020"

print(df)

In [ ]:
mod_fecha = df['Fecha'].mode()

print(mod_fecha)

In [ ]:
df['Fecha'].fillna(mod_fecha.to_string(), inplace=True)

print(df)

In [ ]:
df_sin_vacios = df.dropna()

print(df_sin_vacios.to_string())

In [ ]:
df.dropna(inplace= True)

print(df.to_string())

In [ ]:
print(df.to_string())

In [ ]:
df_relleno = df.fillna("Sin registro")

print(df_relleno.to_string())

In [ ]:
df_cero = df["Ingresos"].fillna(0)

print(df_cero)

In [ ]:
media = df["Ingresos"].mean()

print(media)

In [ ]:
df_media = df["Ingresos"].fillna(media)

print(df_media)

In [ ]:
mediana = df["Ingresos"].median()

print(mediana)

In [ ]:
df_mediana = df["Ingresos"].fillna(mediana)

print(df_mediana)

In [ ]:
moda = df["Ingresos"].mode()

print(moda)

In [ ]:
df_moda = df["Ingresos"].fillna(moda)

print(df_moda)

In [ ]:
df.loc[1, "Peso"] = 70

print(df)

In [ ]:
data = {
    'Nombre': ['Juan', 'María', 'Pedro', 'Ana', 'Luis', 'Luis'],
    'Edad': [25, 32, None, 42, 28, 28],
    'Fecha': ['31/01/2020', '31/01/2020', None, '31/01/2020', '01/31/2020', '01/31/2020'],
    'Género': ['M', 'F', None, 'F', 'M', 'M'],
    'Ciudad': ['Madrid', None, 'Madrid', 'Valencia', 'Barcelona','Barcelona'],
    'Altura': [175, 163, 180, 158, 170, 170],
    'Peso': [70, None, 80, 60, 75, 75],
    'Ingresos': [50000, 60000, 40000, None, 55000, 55000]
}

In [ ]:
df = pd.DataFrame(data)

df

In [ ]:
df.duplicated()

In [ ]:
df.drop_duplicates(inplace= True)

df

In [ ]:
data = {
    'A': [1, 2, 3, 4, 5],
    'B': [5, 4, 3, 2, 1],
    'C': [2, 4, 6, 8, 10]
}

In [ ]:
df = pd.DataFrame(data)

In [ ]:
df.corr()

# Matplotlib

In [ ]:
# pip install matplotlib

In [ ]:
import matplotlib as plt

In [ ]:
import matplotlib.pyplot as plt

## Plot

In [ ]:
import numpy as np

puntos_x = np.array([0, 4, 8, 16])

puntos_y = np.array([6, 12, 24, 48])

plt.plot(puntos_x, puntos_y)

plt.show()

In [ ]:
x1 = np.array([0, 1, 2, 3])
y1 = np.array([3, 8, 1, 10])
x2 = np.array([0, 1, 2, 3])
y2 = np.array([6, 2, 7, 11])

plt.plot(x1, y1, x2, y2)
plt.show()

In [ ]:
y1 = np.array([3, 8, 1, 10])
y2 = np.array([6, 2, 7, 11])

plt.plot(y1)
plt.plot(y2)

plt.show()

## Formato

In [ ]:
puntos_y = np.array([6, 12, 24, 48])

plt.plot(puntos_y, 'o')

plt.show()

In [ ]:
plt.plot(puntos_x, puntos_y, 'x')

plt.show()

# Marcador

# 'o'
# '*'
# '.'
# ','
# 'x'
# 'X'
# '+'	
# 'P'	
# 's'
# 'D'
# 'd'	
# 'p'	
# 'H'
# 'h'
# 'v'
# '^'
# '<'	
# '>'	
# '1'	
# '2'
# '3'	
# '4'	
# '|'
# '_'

In [ ]:
plt.plot(puntos_x, puntos_y, '-.')

plt.show()


# Línea

# '-'
# ':'
# '--'		
# '-.'

In [ ]:
plt.plot(puntos_x, puntos_y, 'g')

plt.show()

# Color

# 'r'
# 'g'
# 'b'
# 'c'
# 'm'
# 'y'
# 'k'
# 'w'

In [ ]:
plt.plot(puntos_x, puntos_y, '*-.r')

plt.show()

In [ ]:
plt.plot(puntos_x, puntos_y, 'o--k', ms=16, mec= 'r', linewidth= '16')

plt.show()

## Descripción

In [ ]:
x = np.array([80, 85, 90, 95, 100, 105, 110, 115, 120, 125])
y = np.array([240, 250, 260, 270, 280, 290, 300, 310, 320, 330])

plt.plot(x, y)

plt.title("Estadísticas Deportivas")

plt.xlabel("Pulso Promedio")

plt.ylabel("Quema de Calorías")

plt.show()

In [ ]:
plt.plot(x, y)

font1 = {'family':'serif','color':'blue','size':20}
font2 = {'family':'serif','color':'darkred','size':15}

plt.title("Estadísticas Deportivas", fontdict=font1)

plt.xlabel("Pulso Promedio", fontdict=font2)

plt.ylabel("Quema de Calorías", fontdict=font2)

plt.show()

In [ ]:
plt.title("Estadísticas Deportivas", loc="center")
plt.xlabel("Pulso Promedio")
plt.ylabel("Quema de Calorías")

plt.plot(x, y)
plt.show()

## Grid

In [ ]:
x = np.array([80, 85, 90, 95, 100, 105, 110, 115, 120, 125])
y = np.array([240, 250, 260, 270, 280, 290, 300, 310, 320, 330])

plt.title("Estadísticas Deportivas")
plt.xlabel("Pulso Promedio")
plt.ylabel("Quema de Calorías")

plt.plot(x, y)

plt.grid()

plt.show()

In [ ]:
x = np.array([80, 85, 90, 95, 100, 105, 110, 115, 120, 125])
y = np.array([240, 250, 260, 270, 280, 290, 300, 310, 320, 330])

plt.title("Estadísticas Deportivas")
plt.xlabel("Pulso Promedio")
plt.ylabel("Quema de Calorías")

plt.plot(x, y)

plt.grid(axis= 'x', linestyle= '--', linewidth= 1)

plt.show()

## Multiples gráficos

In [ ]:
#plot 1:
x = np.array([0, 1, 2, 3])
y = np.array([3, 8, 1, 10])

plt.subplot(1, 2, 2)
plt.plot(x,y)

#plot 2:
x = np.array([0, 1, 2, 3])
y = np.array([10, 20, 30, 40])

plt.subplot(1, 2, 1)
plt.plot(x,y)

plt.show()

In [ ]:
#plot 1:
x = np.array([0, 1, 2, 3])
y = np.array([3, 8, 1, 10])

plt.subplot(2, 1, 2)
plt.plot(x,y)

#plot 2:
x = np.array([0, 1, 2, 3])
y = np.array([10, 20, 30, 40])

plt.subplot(2, 1, 1)
plt.plot(x,y)

plt.show()

In [ ]:
x = np.array([0, 1, 2, 3])
y = np.array([3, 8, 1, 10])

plt.subplot(2, 3, 1)
plt.plot(x,y)

x = np.array([0, 1, 2, 3])
y = np.array([10, 20, 30, 40])

plt.subplot(2, 3, 2)
plt.plot(x,y)

x = np.array([0, 1, 2, 3])
y = np.array([3, 8, 1, 10])

plt.subplot(2, 3, 3)
plt.plot(x,y)

x = np.array([0, 1, 2, 3])
y = np.array([10, 20, 30, 40])

plt.subplot(2, 3, 4)
plt.plot(x,y)

x = np.array([0, 1, 2, 3])
y = np.array([3, 8, 1, 10])

plt.subplot(2, 3, 5)
plt.plot(x,y)

x = np.array([0, 1, 2, 3])
y = np.array([10, 20, 30, 40])

plt.subplot(2, 3, 6)
plt.plot(x,y)

plt.show()

In [ ]:
#plot 1:
x = np.array([0, 1, 2, 3])
y = np.array([3, 8, 1, 10])

plt.subplot(1, 2, 1)
plt.plot(x,y)
plt.title("VENTAS")

#plot 2:
x = np.array([0, 1, 2, 3])
y = np.array([10, 20, 30, 40])

plt.subplot(1, 2, 2)
plt.plot(x,y)
plt.title("INGRESOS")

plt.show()

In [ ]:
#plot 1:
x = np.array([0, 1, 2, 3])
y = np.array([3, 8, 1, 10])

plt.subplot(1, 2, 1)
plt.plot(x,y)
plt.title("VENTAS")

#plot 2:
x = np.array([0, 1, 2, 3])
y = np.array([10, 20, 30, 40])

plt.subplot(1, 2, 2)
plt.plot(x,y)
plt.title("INGRESOS")

plt.suptitle("2023")
plt.savefig('ejemplo.png')
plt.savefig('ejemplo.pdf')
plt.savefig('ejemplo.svg')
plt.show()

## Scatter

In [ ]:
x = np.array([5,7,8,7,2,17,2,9,4,11,12,9,6])
y = np.array([99,86,87,88,111,86,103,87,94,78,77,85,86])

plt.scatter(x, y)

plt.show()

In [ ]:
#day one, the age and speed of 13 cars:
x = np.array([5,7,8,7,2,17,2,9,4,11,12,9,6])
y = np.array([99,86,87,88,111,86,103,87,94,78,77,85,86])
plt.scatter(x, y)

#day two, the age and speed of 15 cars:
x = np.array([2,2,8,1,15,8,12,9,7,3,11,4,7,14,12])
y = np.array([100,105,84,105,90,99,90,95,94,100,79,112,91,80,85])
plt.scatter(x, y)

plt.show()

In [ ]:
x = np.array([5,7,8,7,2,17,2,9,4,11,12,9,6])
y = np.array([99,86,87,88,111,86,103,87,94,78,77,85,86])

plt.scatter(x, y, color = 'r')

x = np.array([2,2,8,1,15,8,12,9,7,3,11,4,7,14,12])
y = np.array([100,105,84,105,90,99,90,95,94,100,79,112,91,80,85])

plt.scatter(x, y, color = '#88c999')

plt.show()

In [ ]:
x = np.array([5,7,8,7,2,17,2,9,4,11,12,9,6])

y = np.array([99,86,87,88,111,86,103,87,94,78,77,85,86])

colors = np.array(["red","green","blue","yellow","pink","black","orange","purple","beige","brown","gray","cyan","magenta"])

plt.scatter(x, y, c=colors)

plt.show()

In [ ]:
x = np.array([5,7,8,7,2,17,2,9,4,11,12,9,6])

y = np.array([99,86,87,88,111,86,103,87,94,78,77,85,86])

sizes = np.array([20,50,100,200,500,1000,60,90,10,300,600,800,75])

plt.scatter(x, y, s=sizes)

plt.show()

In [ ]:
x = np.array([5,7,8,7,2,17,2,9,4,11,12,9,6])

y = np.array([99,86,87,88,111,86,103,87,94,78,77,85,86])

sizes = np.array([20,50,100,200,500,1000,60,90,10,300,600,800,75])

plt.scatter(x, y, s=sizes, alpha=0.9)

plt.show()

In [ ]:
x = np.random.randint(100, size=(100))

y = np.random.randint(100, size=(100))

colors = np.random.randint(100, size=(100))

sizes = 10 * np.random.randint(100, size=(100))

plt.scatter(x, y, c=colors, s=sizes, alpha=0.5, cmap='twilight')

plt.colorbar()

plt.show()

In [ ]:
x = np.array([5,7,8,7,2,17,2,9,4,11,12,9,6])

y = np.array([99,86,87,88,111,86,103,87,94,78,77,85,86])

colors = np.array([0, 10, 20, 30, 40, 45, 50, 55, 60, 70, 80, 90, 100])

plt.scatter(x, y, c=colors, cmap='viridis')

plt.colorbar()

plt.show()

## Barra

In [ ]:
x = np.array(["A", "B", "C", "D"])

y = np.array([3, 8, 1, 10])

plt.bar(x,y)

plt.show()

In [ ]:
x = np.array(["A", "B", "C", "D"])
y = np.array([3, 8, 1, 10])

plt.bar(x, y, color= "blue")

plt.show()

In [ ]:
x = np.array(["A", "B", "C", "D"])
y = np.array([3, 8, 1, 10])

plt.bar(x, y, width = 0.1)
plt.show()

In [ ]:
x = np.array(["A", "B", "C", "D"])

y = np.array([3, 8, 1, 10])

plt.barh(x, y)

plt.show()

In [ ]:
x = np.array(["A", "B", "C", "D"])
y = np.array([3, 8, 1, 10])

plt.barh(x, y, height = 0.1)
plt.show()

## Histograma

In [ ]:
x = np.random.normal(170, 10, 250)

plt.hist(x)

plt.show()

## Pastel

In [ ]:
y = np.array([35, 25, 25, 15])

plt.pie(y)

plt.show()

In [ ]:
y = np.array([35, 25, 25, 15])

mylabels = ["Manzanas", "Bananas", "Cerezas", "Naranjas"]

plt.pie(y, labels = mylabels)

plt.show()

In [ ]:
y = np.array([35, 25, 25, 15])

mylabels = ["Manzanas", "Bananas", "Cerezas", "Naranjas"]

mycolors = ["green", "yellow", "red", "orange"]

plt.pie(y, labels = mylabels, colors = mycolors)

plt.show()

In [ ]:
y = np.array([35, 25, 25, 15])

mylabels = ["Manzanas", "Bananas", "Cerezas", "Naranjas"]

mycolors = ["green", "yellow", "red", "orange"]

myexplode = [0.2, 0, 0, 0]

plt.pie(y, labels = mylabels, colors = mycolors, explode = myexplode)

plt.show()

In [ ]:
y = np.array([35, 25, 25, 15])

mylabels = ["Manzanas", "Bananas", "Cerezas", "Naranjas"]

mycolors = ["green", "yellow", "red", "orange"]

plt.pie(y, labels = mylabels, colors = mycolors)

plt.legend(title="Leyenda")

plt.show()

## Salary Data

In [ ]:
df = pd.read_csv("../dataset/Salary_Data.csv")

print(df.to_string())

In [ ]:
df.info()

In [ ]:
df

In [ ]:
valor_max = df['Age'].max()

print(valor_max)

In [ ]:
df[df['Age'] == 62.0]