# Numpy

# Hola Jupyter Notebook
## Hola Jupyter Notebook
### Hola Jupyter Notebook
#### Hola Jupyter Notebook
##### Hola Jupyter Notebook

In [186]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [187]:
import numpy as np

# Arreglos

In [188]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [189]:
arr = np.array(([1,2,3],[4,5,6]))
print(arr)

[[1 2 3]
 [4 5 6]]


In [190]:
arr = np.array(([1,2,3],[4,5,6],[7,8,9]))
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [191]:
arr = np.array([1,2,3,4,5,6,7,8,9], ndmin=3)

print(arr.ndim)

print(arr)
print(arr[0])
print(arr[0][0])
print(arr[0][0][0])

    

3
[[[1 2 3 4 5 6 7 8 9]]]
[[1 2 3 4 5 6 7 8 9]]
[1 2 3 4 5 6 7 8 9]
1


In [192]:
arr = np.zeros((2,2))

print(arr)

[[0. 0.]
 [0. 0.]]


In [193]:
arr = np.zeros((3,3))

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [194]:
arr = np.zeros((4,4))

print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [195]:
arr = np.zeros((5,5))

print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [196]:
arr = np.zeros((5,1))

print(arr)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [197]:
arr = np.zeros((5,2))

print(arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [198]:
arr = np.zeros((5,3))

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [199]:
arr = np.zeros((5,4))

print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [200]:
arr = np.zeros((1,5))

print(arr)

[[0. 0. 0. 0. 0.]]


In [201]:
arr = np.zeros((2,5))

print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [202]:
arr = np.zeros((3,5))

print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [203]:
arr = np.zeros((4,5))

print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [204]:
arr = np.zeros((5,5))

print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [205]:
arr = np.ones((5,5))

print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [206]:
arr = np.ones((15,15))

print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [207]:
arr = np.zeros((2,2))

print(arr)

[[0. 0.]
 [0. 0.]]


In [208]:
arr = np.zeros((3,3))

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [209]:
arr = np.zeros((3,3))

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [210]:
arr = np.zeros((4,4))

print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [211]:
arr = np.zeros((5,5))

print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [212]:
arr = np.zeros((5,4))

print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [213]:
arr = np.zeros((5,3))

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [214]:
arr = np.zeros((5,2))

print(arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [215]:
arr = np.zeros((5,1))

print(arr)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [216]:
arr = np.zeros((4,5))

print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [217]:
arr = np.zeros((3,5))

print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [218]:
arr = np.zeros((2,5))

print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [219]:
arr = np.zeros((1,5))

print(arr)

[[0. 0. 0. 0. 0.]]


In [220]:
arr = np.random.rand(1,1)

print(arr)

[[0.55344206]]


In [221]:
arr = np.random.rand(2,2)

print(arr)

[[0.05498843 0.43164611]
 [0.07222358 0.35536383]]


In [222]:
arr = np.random.rand(3,3)

print(arr)

[[0.01537217 0.58371391 0.1240756 ]
 [0.25859098 0.59134456 0.14340103]
 [0.95230377 0.17720647 0.89310677]]


In [223]:
arr = np.random.rand(4,4)

print(arr)

[[0.55001141 0.02277189 0.72726735 0.89110696]
 [0.67291523 0.22614594 0.64573406 0.88694267]
 [0.97231574 0.352789   0.76845281 0.46390231]
 [0.05615407 0.41703067 0.50941333 0.61101426]]


In [224]:
arr = np.random.rand(5,5)

print(arr)

[[0.92655451 0.63423658 0.50606652 0.88292858 0.41191647]
 [0.99506838 0.13523316 0.49664078 0.85316366 0.66380804]
 [0.6770325  0.80834167 0.03470581 0.52015837 0.00209063]
 [0.20221677 0.16629607 0.59269214 0.92832852 0.94017763]
 [0.7021508  0.6216848  0.02469383 0.97811709 0.20309315]]


# Operaciones aritméticas con Arreglos

### Suma

In [225]:
arr00 = [1,2,3]
arr01 = [4,5,6]

arr03 = np.add(arr00,arr01)

print(arr03)

[5 7 9]


### Resta

In [226]:
arr00 = [1,2,3]
arr01 = [4,5,6]

arr03 = np.subtract(arr01,arr00)

print(arr03)

[3 3 3]


### Multiplicacion

In [227]:
arr00 = [1,2,3]
arr01 = [4,5,6]

arr03 = np.multiply(arr01,arr00)

print(arr03)

[ 4 10 18]


### Division

In [228]:
arr00 = [1,2,3]
arr01 = [4,5,6]

arr03 = np.divide(arr01,arr00)

print(arr03)

[4.  2.5 2. ]


# Operaciones de Estadistica con Arreglos

### Media

In [229]:
arr = [1,5,7]

media = np.mean(arr)

print(media)

4.333333333333333


### Mediana

In [230]:
arr = [1,5,7]

mediana = np.mean(arr)            

print(mediana)

4.333333333333333


### Maximo

In [231]:
arr = [1,5,7]

maximo = np.max(arr)            

print(maximo)

7


### Minimo

In [232]:
arr = [1,5,7]

minimo = np.min(arr)            

print(minimo)

1


# Indexación

In [233]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[0])

1


In [234]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[1])

2


In [235]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[2])

3


In [236]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[3])

4


In [237]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[4])

5


In [238]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[-1])

10


In [239]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[-1])

10


In [240]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[-2])

9


In [241]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[-3])

8


In [242]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[-4])

7


In [243]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[-5])

6


In [244]:
arr = np.array(([1,2,3],[4,5,6]))

print(arr[1,1])

5


In [245]:
arr = np.array(([1,2,3],[4,5,6]))

print(arr[0,0])
print(arr[0,1])
print(arr[0,2])
print("")
print(arr[1,0])
print(arr[1,1])
print(arr[1,2])



1
2
3

4
5
6


In [246]:
arr = np.array((1,2,3,4,5,6))

print(arr[1:4])


[2 3 4]


In [247]:
arr = np.array((1,2,3,4,5,6))

print(arr[1:4:2])

[2 4]


In [248]:
arr = np.array((1,2,3,4,5,6,7,8,9,10))

print(arr[0:8:2])

[1 3 5 7]


In [249]:
arr = np.array((1,2,3,4,5,6,7,8,9,10,11,12))

print(arr[0:7:2])

[1 3 5 7]


In [250]:
arr = np.array((1,2,3,4,5,6,7,8,9,10,11,12))

print(arr[::])

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [251]:
arr = np.array((1,2,3,4,5,6,7,8,9,10,11,12))

print(arr[::1])

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [252]:
arr = np.array((1,2,3,4,5,6,7,8,9,10,11,12))

print(arr[::2])

[ 1  3  5  7  9 11]


In [253]:
arr = np.array((1,2,3,4,5,6,7,8,9,10,11,12))

print(arr[::3])

[ 1  4  7 10]


# Slicing

In [254]:
arr = np.array((1,2,3,4,5,6,7,8,9,10,11,12,13,14,15))

print(arr[1::2])

[ 2  4  6  8 10 12 14]


In [255]:
arr = np.array((1,2,3,4,5,6,7,8,9,10,11,12,13,14,15))

print(arr[1::3])

[ 2  5  8 11 14]


In [256]:
arr = np.array((1,2,3,4,5,6,7,8,9,10,11,12,13,14,15))

print(arr[1::4])

[ 2  6 10 14]
